#ifndef Constant_hpp
#define Constant_hpp

#define LOG_LEVEL 190

#define UNITTEST_ID "UNITTESTCHECK"

#define SERVER_SOCKET "/var/run/WCDXMsgServer"

#define MSG_SERVER_VERSION "v0.2alpha"

#define MSG_INDICATOR_GET "GET"
#define MSG_INDICATOR_SET "SET"

#define RECEIVER_PROCESS_PER_LOOP_COUNT 128
#define MSGPROCESSOR_PROCESS_PER_LOOP_COUNT 256

#define SESSION_ID_BYTES 64

#define CLIENTS_MAX 1024
#define NET_BACKLOG CLIENTS_MAX

#define MSGBUFFER_SIZE 1024*8

#define PROCESS_MESSAGES_IN_MAX CLIENTS_MAX*4

#define MSG_PER_SESSION_MAX 32

#define CLIENTLIB_TRANSMIT_RETRY_COUNT 360
#define CLIENTLIB_TRANSMIT_RETRY_SLEEP_INTERVAL_SEC 10

#define LOCK_STATE_WROTE_QUEUE 1
#define LOCK_STATE_PROCESSED_QUEUE 2

#define RUN_GROUP_ID 2000
#define RUN_USER_ID 2000

#endif
